In [1]:
import numpy as np 
import packages.grid as gd
import packages.grid as gd
import packages.path as pth
import pdb
import sys
sys.path.insert(1, 'D:\AAlearnAA\Study\python')
from rutaul.prnt import pg,pm,pr,py,pb

class vertix():
    def __init__(self,  location:tuple, camefrom:tuple , time:int):
        self.location = location
        self.camefrom = camefrom
        self.time = time
    def __repr__(self):
        return f'Vertix a {self.location} -> {self.camefrom} Time: {self.time} '





# ------------------- Creating the random grid
gridsize = (8,8)

d = gd.gridgen(gridsize) # Creating the grid ................ and initializing the nodes distancd to infinity or very high number .. 99999
infin = 999999
d.reachedpointgrid = infin * np.ones(gridsize).astype(int)

gridlength, gridwidth = gridsize
dij_list = []
processed_vertices = []



def findvertix_update(updatever: vertix):
    pr('UPDATE') 
    found= False
    i = 0
    for ver in dij_list:
        if not found:
            if updatever.time < ver.time:
                dij_list.insert(i,updatever)
                if updatever.location == ver.location:
                    dij_list.remove(ver)
                    break
                found = True
        else:
            if updatever.location == ver.location:
                dij_list.remove(ver)
                break
        i +=1

def checkconnection( ver:vertix):
    x,y = ver.location
    lst = []

    def add(X,Y):
        # pdb.set_trace()
        if (X,Y)  != ver.camefrom:
            time2reach = ver.time + d.grid[X][Y]
            # pdb.set_trace()
            if time2reach < d.reachedpointgrid[X][Y]:
                if infin == d.reachedpointgrid[X][Y]:
                    d.reachedpointgrid[X][Y] = time2reach
                    lst.append(vertix((X,Y),ver.location,time2reach))
                else:
                    findvertix_update(vertix((X,Y),ver.location,time2reach))

                

    if  x- 1 >= 0: # -- CHECK THE GRID DIMENESION
        add( x-1,y)
    if x + 1 < gridlength:# -- CHECK THE GRID DIMENESION
        pg('CALLING ADD DOWN')
        # pdb.set_trace()
        add(x+1,y)

    if y + 1 < gridwidth:# -- CHECK THE GRID DIMENESION
        pg('CALLING ADD RIGHT')
        add( x, y+1)
    
    if y - 1 >= 0:  # -- CHECK THE GRID DIMENESION
        add(x, y-1)

    return lst


def dijkstra():
    # The algorithm will start from 0,0
    # for row in range(0, gridlength):
    #     for cell in row:
    #         conectedvertices vertixConection()
   



        # map(lambda x: lst.remove(x) if x.comefrom == ver.location , lst)
    
    d.reachedpointgrid[0][0] = d.grid[0][0]

    dij_list.append(vertix((0,0), (0,0) , d.grid[0][0]))
    while len(dij_list) > 0:
        py(dij_list)
        print('welcome')
        if dij_list[0].location == (gridlength-1,gridwidth-1):
            print('wow')
            print('wow')
            print('wow')
            print('wow')
            loop = True
            path = '' + str(dij_list[0].location)
            pointer = dij_list[0]
            while loop:
                if pointer.camefrom == (0,0):
                    path = path +" -> "+ str(pointer.camefrom)
                    break
                else:
                    path = path +" -> " +str(pointer.camefrom)
                    pointer = pointer.camefrom
                
            pm(path)


            break
        else:
            connectedvertices = checkconnection(dij_list[0])
            
            i = 1
            notinserted = True
            pr(d.reachedpointgrid)
            for ver in connectedvertices:
                notinserted = True
                for i in range(1,len(dij_list)):
                    if ver.time < dij_list[i].time:
                        dij_list.insert( i, ver)
                        notinserted = False
                        break
                if notinserted:
                    dij_list.append(ver)
            
            connectedvertices = []
                
            pg(d.reachedpointgrid)
            processed_vertices.append(dij_list.pop(0))
            
        
        
pb(d.grid)
dijkstra()




........... 🆂  🆃  🅰   🆁  🆃 ...........
[[6 9 8 9 7 7 4 1]
 [8 4 2 8 8 8 5 8]
 [0 4 2 1 9 8 6 0]
 [9 9 2 0 8 3 0 1]
 [4 6 1 5 9 0 5 1]
 [1 1 6 4 4 4 1 5]
 [9 7 6 3 8 8 3 2]
 [4 8 5 2 9 9 9 6]]
[Vertix a (0, 0) -> (0, 0) Time: 6 ]
welcome
CALLING ADD DOWN
CALLING ADD RIGHT
[[     6     15 999999 999999 999999 999999 999999 999999]
 [    14 999999 999999 999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999 999999 999999 999999]]
[[     6     15 999999 999999 999999 999999 999999 999999]
 [    14 999999 999999 999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999 999999 999999 999999]
 [999999 999999 9

AttributeError: 'tuple' object has no attribute 'camefrom'

In [3]:
import numpy as np 
import packages.grid as gd
import packages.grid as gd
import packages.path as pth
import pdb
import sys
sys.path.insert(1, 'D:\AAlearnAA\Study\python')
from rutaul.prnt import pg,pm,pr,py,pb

class vertix():
    def __init__(self,  location:tuple, camefrom , time:int):
        self.location = location
        self.camefrom = camefrom
        self.time = time
    def __repr__(self):
        return f'Vertix a {self.location} -> {self.camefrom} Time: {self.time} '





# ------------------- Creating the random grid
gridsize = (3,3)

d = gd.gridgen(gridsize) # Creating the grid ................ and initializing the nodes distancd to infinity or very high number .. 99999


# gridsize = d.jiktest()
# gridsize = d.fillreallynaughtyLEFTUP()

infin = 999999
d.reachedpointgrid = infin * np.ones(gridsize).astype(int)
gridlength, gridwidth = gridsize
dij_list = []
processed_vertices = []



def findvertix_update(updatever: vertix):
    pr('UPDATE')

    pr('UPDATE')
    found= False
    i = 0
    for ver in dij_list:
        if not found:
            if updatever.time < ver.time:
                dij_list.insert(i,updatever)
                if updatever.location == ver.location:
                    dij_list.remove(ver)
                    break
                found = True
        else:
            if updatever.location == ver.location:
                dij_list.remove(ver)
                break
        i +=1

def checkconnection( ver:vertix):
    x,y = ver.location
    lst = []

    def add(X,Y):
        # pdb.set_trace()
        if (X,Y)  != ver.camefrom.location:
            time2reach = ver.time + d.grid[X][Y]
            # pdb.set_trace()
            if time2reach < d.reachedpointgrid[X][Y]:
                if infin == d.reachedpointgrid[X][Y]:
                    d.reachedpointgrid[X][Y] = time2reach
                    lst.append(vertix((X,Y),ver,time2reach))
                else:
                    findvertix_update(vertix((X,Y),ver,time2reach))

                

    if  x- 1 >= 0: # -- CHECK THE GRID DIMENESION
        add( x-1,y)
    if x + 1 < gridlength:# -- CHECK THE GRID DIMENESION
        pg('CALLING ADD DOWN')
        # pdb.set_trace()
        add(x+1,y)

    if y + 1 < gridwidth:# -- CHECK THE GRID DIMENESION
        pg('CALLING ADD RIGHT')
        add( x, y+1)
    
    if y - 1 >= 0:  # -- CHECK THE GRID DIMENESION
        add(x, y-1)

    return lst


def dijkstra():
    # The algorithm will start from 0,0
    # for row in range(0, gridlength):
    #     for cell in row:
    #         conectedvertices vertixConection()
   



        # map(lambda x: lst.remove(x) if x.comefrom == ver.location , lst)
    

    d.reachedpointgrid[0][0] = d.grid[0][0]

    dij_list.append(vertix((0,0), vertix((-1,-1),None,0) , d.grid[0][0]))
    while len(dij_list) > 0:
        py(dij_list)
        print('welcome')
        if dij_list[0].location == (gridlength-1,gridwidth-1):
            print('wow')
            print('wow')
            print('wow')
            print('wow')
            loop = True
            path = '' + str(dij_list[0].location)
            pointer = dij_list[0]
            while loop:
                if pointer.camefrom.location == (0,0):
                    path = path +" <- "+ str(pointer.camefrom.location)
                    break
                else:
                    path = path +" <- " +str(pointer.camefrom.location)
                    pointer = pointer.camefrom
                
            pm(path)


            break
        else:
            connectedvertices = checkconnection(dij_list[0])
            
            i = 1
            notinserted = True
            pr(d.reachedpointgrid)
            for ver in connectedvertices:
                notinserted = True
                for i in range(1,len(dij_list)):
                    if ver.time < dij_list[i].time:
                        dij_list.insert( i, ver)
                        notinserted = False
                        break
                if notinserted:
                    dij_list.append(ver)
            
            connectedvertices = []
                
            pg(d.reachedpointgrid)
            processed_vertices.append(dij_list.pop(0))
            
        
        
pb(d.grid)
dijkstra()


[[2 0 0 0 0]
 [3 3 1 2 0]
 [0 0 0 0 0]
 [0 1 9 1 1]
 [0 0 0 0 0]]
[Vertix a (0, 0) -> Vertix a (-1, -1) -> None Time: 0  Time: 2 ]
welcome
CALLING ADD DOWN
CALLING ADD RIGHT
[[     2      2 999999 999999 999999]
 [     5 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999]]
[[     2      2 999999 999999 999999]
 [     5 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999]]
[Vertix a (0, 1) -> Vertix a (0, 0) -> Vertix a (-1, -1) -> None Time: 0  Time: 2  Time: 2 , Vertix a (1, 0) -> Vertix a (0, 0) -> Vertix a (-1, -1) -> None Time: 0  Time: 2  Time: 5 ]
welcome
CALLING ADD DOWN
CALLING ADD RIGHT
[[     2      2      2 999999 999999]
 [     5      5 999999 999999 999999]
 [999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999]
 [999999 999999 999999 999999 999999]]
[[     2      2      2 99