# $$ Dijkstra $$

In [4]:
import numpy as np 
import packages.grid as gd
import packages.grid as gd
import packages.path as pth
import pdb
import sys
sys.path.insert(1, 'D:\AAlearnAA\Study\python')
from rutaul.prnt import pg,pm,pr,py,pb

class vertix():
    def __init__(self,  location:tuple, camefrom , time:int):
        self.location = location
        self.camefrom = camefrom
        self.time = time
    def __repr__(self):
        return f'Vertix a {self.location} -> {self.camefrom} Time: {self.time} '





# ------------------- Creating the random grid
gridsize = (80,50)

d = gd.gridgen(gridsize) # Creating the grid ................ and initializing the nodes distancd to infinity or very high number .. 99999


# gridsize = d.jiktest()
# gridsize = d.fillreallynaughtyLEFTUP()

infin = 999999
d.reachedpointgrid = infin * np.ones(gridsize).astype(int)
gridlength, gridwidth = gridsize
dij_list = []
processed_vertices = []



def findvertix_update(updatever: vertix):
    found= False
    i = 0
    for ver in dij_list:
        if not found:
            if updatever.time < ver.time:
                dij_list.insert(i,updatever)
                if updatever.location == ver.location:
                    dij_list.remove(ver)
                    break
                found = True
        else:
            if updatever.location == ver.location:
                dij_list.remove(ver)
                break
        i +=1

def checkconnection( ver:vertix):
    x,y = ver.location
    lst = []

    def add(X,Y):
        # pdb.set_trace()
        if (X,Y)  != ver.camefrom.location:
            time2reach = ver.time + d.grid[X][Y]
            # pdb.set_trace()
            if time2reach < d.reachedpointgrid[X][Y]:
                if infin == d.reachedpointgrid[X][Y]:
                    d.reachedpointgrid[X][Y] = time2reach
                    lst.append(vertix((X,Y),ver,time2reach))
                else:
                    findvertix_update(vertix((X,Y),ver,time2reach))

                

    if  x- 1 >= 0: # -- CHECK THE GRID DIMENESION Then add the node to ABOVE
        add( x-1,y)

    if x + 1 < gridlength:# -- CHECK THE GRID DIMENESION Then add the node to BELOW
        # pg('CALLING ADD DOWN')
        # pdb.set_trace()
        add(x+1,y)

    if y + 1 < gridwidth:# -- CHECK THE GRID DIMENESION Then add the node to the RIGHT
        # pg('CALLING ADD RIGHT')
        add( x, y+1)
    
    if y - 1 >= 0:  # -- CHECK THE GRID DIMENESION Then add the node to the LEFT
        add(x, y-1)

    return lst

def drawpath(path2start):
    pm(" Dɪᴊᴋsᴛʀᴀ's ᴀʟɢᴏʀɪᴛʜᴍ ")
    grid = d.grid.tolist()
    z = np.ones(gridsize).astype(int)

    import matplotlib
    import matplotlib.pyplot as plt
    from matplotlib.colors import BoundaryNorm
    from matplotlib.ticker import MaxNLocator
    t = 0
    for cell in path2start:
        grid[cell[0]][cell[1]] = '-'
        z[gridlength- 1- cell[0]][cell[1]] = t
        # t+=1
 
    
    x = np.arange(-.5, gridlength+.5, 1)  # len = 11
    y = np.arange(-.5, gridwidth+.5, 1)  # len = 7
    cmap = plt.get_cmap('Spectral')  #
    plt.axis('off')
    # pdb.set_trace()

    plt.style.use('dark_background')
    z.reshape(gridwidth,gridlength)
    plt.pcolormesh(y, x, z, cmap=cmap, edgecolor='black',snap= True)

    # pdb.set_trace()

    for row in range(0, gridlength):
        for cell in range(0, gridwidth):

            plt.text(cell, row, d.grid[gridlength - row-1][cell], color='white', ha='center', va='center', fontsize=10)
    # pdb.set_trace()

def dijkstra():
    # The algorithm will start from 0,0
    # for row in range(0, gridlength):
    #     for cell in row:
    #         conectedvertices vertixConection()
   


        # map(lambda x: lst.remove(x) if x.comefrom == ver.location , lst)
    

    d.reachedpointgrid[0][0] = d.grid[0][0]

    dij_list.append(vertix((0,0), vertix((-1,-1),None,0) , d.grid[0][0]))
    while len(dij_list) > 0:
        if dij_list[0].location == (gridlength-1,gridwidth-1):
            py(dij_list)
            pr('Shortest Path Found')
            loop = True
            path = '' + str(dij_list[0].location)
            pointer = dij_list[0]
            path2start = [dij_list[0].location]
            while loop:

                path2start.append(pointer.camefrom.location)

                if pointer.camefrom.location == (0,0):
                    path = path +" <- "+ str(pointer.camefrom.location)
                    drawpath(path2start)
                    break
                else:
                    path = path +" <- " +str(pointer.camefrom.location)
                    pointer = pointer.camefrom
            pm(path)
            break
        else:
            connectedvertices = checkconnection(dij_list[0])
            
            i = 1
            notinserted = True
            # pr(d.reachedpointgrid)
            for ver in connectedvertices:
                notinserted = True
                for i in range(1,len(dij_list)):
                    if ver.time < dij_list[i].time:
                        dij_list.insert( i, ver)
                        notinserted = False
                        break
                if notinserted:
                    dij_list.append(ver)
            
            connectedvertices = []
            # pg(d.reachedpointgrid)
            processed_vertices.append(dij_list.pop(0))
            
        
        
pb(d.grid)
dijkstra()


[[0 2 2 ... 0 1 0]
 [2 9 6 ... 4 2 1]
 [6 4 7 ... 6 4 0]
 ...
 [7 1 2 ... 2 6 2]
 [0 1 6 ... 0 0 5]
 [0 1 4 ... 2 6 0]]
[Vertix a (79, 49) -> Vertix a (78, 49) -> Vertix a (78, 48) -> Vertix a (78, 47) -> Vertix a (77, 47) -> Vertix a (76, 47) -> Vertix a (76, 46) -> Vertix a (76, 45) -> Vertix a (76, 44) -> Vertix a (76, 43) -> Vertix a (76, 42) -> Vertix a (76, 41) -> Vertix a (76, 40) -> Vertix a (75, 40) -> Vertix a (74, 40) -> Vertix a (73, 40) -> Vertix a (73, 39) -> Vertix a (73, 38) -> Vertix a (72, 38) -> Vertix a (72, 37) -> Vertix a (71, 37) -> Vertix a (70, 37) -> Vertix a (70, 36) -> Vertix a (69, 36) -> Vertix a (68, 36) -> Vertix a (67, 36) -> Vertix a (66, 36) -> Vertix a (65, 36) -> Vertix a (64, 36) -> Vertix a (63, 36) -> Vertix a (62, 36) -> Vertix a (62, 35) -> Vertix a (62, 34) -> Vertix a (62, 33) -> Vertix a (62, 32) -> Vertix a (62, 31) -> Vertix a (62, 30) -> Vertix a (61, 30) -> Vertix a (60, 30) -> Vertix a (59, 30) -> Vertix a (59, 29) -> Vertix a (59, 28) 

KeyboardInterrupt: 